// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PPI_projektas.Utils;

#nullable disable

namespace PPI_projektas.Migrations
{
    [DbContext(typeof(EntityData))]
    [Migration("20231109144753_Relationships")]
    partial class Relationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.Property<Guid>("GroupsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MembersId")
                        .HasColumnType("char(36)");

                    b.HasKey("GroupsId", "MembersId");

                    b.HasIndex("MembersId");

                    b.ToTable("GroupUser");
                });

            modelBuilder.Entity("NoteUser", b =>
                {
                    b.Property<Guid>("FavoriteByUsersId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FavoriteNotesId")
                        .HasColumnType("char(36)");

                    b.HasKey("FavoriteByUsersId", "FavoriteNotesId");

                    b.HasIndex("FavoriteNotesId");

                    b.ToTable("NoteUser");
                });

            modelBuilder.Entity("PPI_projektas.objects.EntityStrings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid?>("NoteId")
                        .HasColumnType("char(36)");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.ToTable("EntityStrings");
                });

            modelBuilder.Entity("PPI_projektas.objects.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("PPI_projektas.objects.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("PPI_projektas.objects.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.HasOne("PPI_projektas.objects.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPI_projektas.objects.User", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NoteUser", b =>
                {
                    b.HasOne("PPI_projektas.objects.User", null)
                        .WithMany()
                        .HasForeignKey("FavoriteByUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPI_projektas.objects.Note", null)
                        .WithMany()
                        .HasForeignKey("FavoriteNotesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PPI_projektas.objects.EntityStrings", b =>
                {
                    b.HasOne("PPI_projektas.objects.Note", null)
                        .WithMany("Tags")
                        .HasForeignKey("NoteId");
                });

            modelBuilder.Entity("PPI_projektas.objects.Group", b =>
                {
                    b.HasOne("PPI_projektas.objects.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PPI_projektas.objects.Note", b =>
                {
                    b.HasOne("PPI_projektas.objects.Group", "Group")
                        .WithMany("Notes")
                        .HasForeignKey("GroupId");

                    b.HasOne("PPI_projektas.objects.User", "User")
                        .WithMany("CreatedNotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PPI_projektas.objects.Group", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("PPI_projektas.objects.Note", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("PPI_projektas.objects.User", b =>
                {
                    b.Navigation("CreatedNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
