// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PPI_projektas.Utils;

#nullable disable

namespace PPI_projektas.Migrations
{
    [DbContext(typeof(EntityData))]
    [Migration("20231218191135_migratePrivileges")]
    partial class migratePrivileges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.Property<Guid>("GroupsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MembersId")
                        .HasColumnType("char(36)");

                    b.HasKey("GroupsId", "MembersId");

                    b.HasIndex("MembersId");

                    b.ToTable("GroupUser");
                });

            modelBuilder.Entity("GroupUser1", b =>
                {
                    b.Property<Guid>("AdministratorOfGroupsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AdministratorsId")
                        .HasColumnType("char(36)");

                    b.HasKey("AdministratorOfGroupsId", "AdministratorsId");

                    b.HasIndex("AdministratorsId");

                    b.ToTable("GroupUser1");
                });

            modelBuilder.Entity("NoteUser", b =>
                {
                    b.Property<Guid>("FavoriteByUsersId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FavoriteNotesId")
                        .HasColumnType("char(36)");

                    b.HasKey("FavoriteByUsersId", "FavoriteNotesId");

                    b.HasIndex("FavoriteNotesId");

                    b.ToTable("NoteUser");
                });

            modelBuilder.Entity("NoteUser1", b =>
                {
                    b.Property<Guid>("EditorOfNotesId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EditorsId")
                        .HasColumnType("char(36)");

                    b.HasKey("EditorOfNotesId", "EditorsId");

                    b.HasIndex("EditorsId");

                    b.ToTable("NoteUser1");
                });

            modelBuilder.Entity("PPI_projektas.objects.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("PPI_projektas.objects.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LastEditTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("PPI_projektas.objects.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("NoteId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("PPI_projektas.objects.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("_email")
                        .HasColumnType("longtext");

                    b.Property<string>("_password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.HasOne("PPI_projektas.objects.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPI_projektas.objects.User", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupUser1", b =>
                {
                    b.HasOne("PPI_projektas.objects.Group", null)
                        .WithMany()
                        .HasForeignKey("AdministratorOfGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPI_projektas.objects.User", null)
                        .WithMany()
                        .HasForeignKey("AdministratorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NoteUser", b =>
                {
                    b.HasOne("PPI_projektas.objects.User", null)
                        .WithMany()
                        .HasForeignKey("FavoriteByUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPI_projektas.objects.Note", null)
                        .WithMany()
                        .HasForeignKey("FavoriteNotesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NoteUser1", b =>
                {
                    b.HasOne("PPI_projektas.objects.Note", null)
                        .WithMany()
                        .HasForeignKey("EditorOfNotesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPI_projektas.objects.User", null)
                        .WithMany()
                        .HasForeignKey("EditorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PPI_projektas.objects.Group", b =>
                {
                    b.HasOne("PPI_projektas.objects.User", "Owner")
                        .WithMany("OwnedGroups")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PPI_projektas.objects.Note", b =>
                {
                    b.HasOne("PPI_projektas.objects.Group", "Group")
                        .WithMany("Notes")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPI_projektas.objects.User", "Author")
                        .WithMany("CreatedNotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("PPI_projektas.objects.Tag", b =>
                {
                    b.HasOne("PPI_projektas.objects.Note", null)
                        .WithMany("Tags")
                        .HasForeignKey("NoteId");
                });

            modelBuilder.Entity("PPI_projektas.objects.Group", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("PPI_projektas.objects.Note", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("PPI_projektas.objects.User", b =>
                {
                    b.Navigation("CreatedNotes");

                    b.Navigation("OwnedGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
